### ISSUE TITLE
Is it possible to not set size field in aggregation part in `collection.json` file

### ISSUE THREAD

**Issue by athlonUA** [itemsapi/itemsapi#131]

**Comment by athlonUA** [comment]
```            
{
                "name": "supplier",
                "type": "terms",
                "field": "supplier",
                "size": 10,  <--- i need to remove this
                "title": "supplier"
}

**Comment by athlonUA** [comment]
and also the problem with huge time of response. especially  if i set this value to 100000 . can you please suggest me some solutions

**Comment by cigolpl** [comment]
Unfortunately probably it is required but actually should not be. I will make it optional in next version.

Anyway if you want to show all suppliers you can set size as "1000" and that should work

**Comment by cigolpl** [comment]
Thats weird, do you have lot of data ? I will look into code later when I will be back.

**Comment by athlonUA** [comment]
yeah, i have about 9M products in elastic

**Comment by athlonUA** [comment]
many products have the same brands and suppliers. but the number of brands or suppliers is equal to more than 10K anyway

**Comment by pilot** [comment]
This is real case, @cigolpl for feature is better to add separate endpoint which allow to get specified filter with the pagination, like `/filter_name/page_number/amounts_per_page`

**Comment by cigolpl** [comment]
@athlonUA I've made a tests and `size` in `terms` filter is not required though. If you don't provide it elasticsearch set it as 10 by default. I would recommend to set size in `itemsapi` to avoid unexpected behaviours. 

I guess the speed issues are caused by memory limits because if you have lot data and want to aggregate that all goes to RAM. 

![selection_448](https://cloud.githubusercontent.com/assets/1032493/16766381/16219e9c-483a-11e6-88f1-73b18863c8ff.jpg)

Possible solutions:
- if you have `ubuntu` you can use `htop` tool to see how much RAM is eaten
- you can also test that with amazon elasticsearch https://aws.amazon.com/elasticsearch-service/. You can create bigger instance in few minutes and test if problem still occur
- add `index`: `not_analyzed` in schema for supplier field 

![selection_450](https://cloud.githubusercontent.com/assets/1032493/16766442/67768988-483a-11e6-9619-f7496e04a326.jpg)

**Comment by cigolpl** [comment]
@pilot do you mean filter like:

`/supplier/mercedes` or `/supplier/mercedes/1/12` ?

**Comment by pilot** [comment]
Exactly, then if I need a full list of suppliers, or I have a page where I list brans present in my store, then easily to list all of them. 

Example 
- List page https://www.amazon.com/Kya-Alyx/dp/B00A27PMLI/ref=sr_1_3?s=instant-video&ie=UTF8&qid=1468326030&sr=1-3&keywords=tv

![amazon com 3a tv 3a amazon video 2016-07-12 15-20-49](https://cloud.githubusercontent.com/assets/28564/16766743/89634d9c-4844-11e6-8ad1-237dae0e423c.png)

- Categories list https://www.amazon.com/gp/search/other/ref=sr_sa_p_n_subscription_id?rh=n%3A2858778011%2Ck%3Atv&bbn=2858778011&keywords=tv&pickerToList=subscription_id&ie=UTF8&qid=1468326030

![amazon com 3a see all results 2016-07-12 15-21-50](https://cloud.githubusercontent.com/assets/28564/16766755/90f8bfb0-4844-11e6-8938-8fcd0e9d37b1.png)

**Comment by pilot** [comment]
@cigolpl about the RAM consuming, yes this is true, but it's shouldn't be the case to how make work api response on the regular instance configuration. 

Of course if you have a huge resource you can cover most of request, but this is not rescue when you have a huge server loading.

**Comment by cigolpl** [comment]
@pilot thanks for those nice examples. yeah, it is great feature!
Creating fast pagination with aggregation on elasticsearch side will be difficult as even they have problem with that: https://github.com/elastic/elasticsearch/issues/4915

ItemsAPI already has endpoint which returns all element for aggregations - `http://localhost:3050/api/v1/facets/collection_name/supplier` which returns something like this:

![selection_451](https://cloud.githubusercontent.com/assets/1032493/16767882/d81ac5e4-4841-11e6-9397-bf09803823d4.jpg)

We can make internal pagination on `ItemsAPI` side like `http://localhost:3050/api/v1/facets/collection_name/supplier?limit=10000&per_page=12&page=1`
Sorry if `facet` name is misleading.

We could even go further and make a cache i.e. `&cache=1&expiration=3600` to cache all 10000 elements internally but it would require providing access to `redis` datastore in config. Not sure yet about caching because that feature is still in testing mode.

Let me know what do you think

**Comment by cigolpl** [comment]
@athlonUA how long usually do you wait for response in that case ?

**Comment by pilot** [comment]
@cigolpl yes, internal pagination will be cool, as well to support drop cache to the redis looks nice solution to working with a lot of data 👍

**Comment by cigolpl** [comment]
Cool you like that. It is very useful feature and I will implement that soon

**Comment by cigolpl** [comment]
The implementation of pagination is done #132. Hope it works for you well

**Comment by cigolpl** [comment]
@athlonUA fyi if you set `size` as 0 it will load all elements in aggregation out of the box.
@pilot @athlonUA: before we implement redis as cache could you make test directly with elasticsearch and your query. It tells us if the performance issue is on `elasticsearch` or `itemsapi` because 9mln records should not be a problem actually. 

1. install sense on google chrome
2. make query

``` js
GET /index_name/_search
{
  "aggs": {
        "supplier": {
          "terms": {
            "field": "supplier",
            "size": 0
          }
        }
    }
}
```

![selection_456](https://cloud.githubusercontent.com/assets/1032493/16781699/b511e510-487c-11e6-8027-36c773071c03.jpg)

I am very curious if that will be much faster because `http://localhost:3050/api/v1/facets/collection_name/supplier` endpoint is not yet super optimized.

**Comment by athlonUA** [comment]
@cigolpl I checked both of these methods. And i prefer the second one with facets. It's more clear and shouldn't required writing additional code on server side. What about response time - it's about 2,5 seconds with parameters like this: size=100K , per_page: 64 . Aggregation works PERFECTLY :+1: but first I was a little confused with server response data when with any parameters i always retrieved 100 objects in buckets. There are no size param in example with facets above. Instead of this the parameter https://github.com/itemsapi/itemsapi/pull/132/commits/03a147a533d16dd3f9c010647ccfd2a2a513af13#diff-27f3d9e315144f3c133792f8aae0cdcbR216 you offered to use limit parameter. ))

Could you help me with another question: how i can sort aggregated data? If I use `sort` parameter with value `asc` all works good. But i'm not sure it's correctly

```
 {
                "name": "brand",
                "type": "terms",
                "field": "brand",
                "size": 0,
                "title": "brand",
                "order": "asc"
 }

**Comment by cigolpl** [comment]
@athlonUA thank you for feedback. I am working on sorting and hopefully finish that at night.
Once finished I send you updated documentation with changes

**Comment by athlonUA** [comment]
:+1:  thanks!

**Comment by cigolpl** [comment]
@athlonUA sorting feature for aggregation is done. you can see more details here: https://itemsapi.readme.io/docs/aggregationscollectionaggregation_name. 

One important thing:
I made an endpoint name `http://localhost:3050/api/v1/aggregations/collection_name/supplier` instead of `http://localhost:3050/api/v1/facets/collection_name/supplier` to be consistent with another part of the system and elasticsearch. Hope that's no problem for you

**Comment by athlonUA** [comment]
I checked sorting feature, all works good! :+1:  Now I have the next problem. How i can to paginate throw aggregated values depended on get items request with query, sort or aggs parameters? The idea is to get only that aggregation items which related to retrieved items in response.

**Comment by cigolpl** [comment]
cool :)  It seems you want to make additional filtering with these aggregation `http://localhost:3050/api/v1/aggregations/collection_name/supplier` results like `http://localhost:3050/api/v1/aggregations/collection_name/supplier?search=italy&aggs={"class":["sport_cars"]}`, is it correct ?

**Comment by cigolpl** [comment]
You can even provide image with your case or example with similar case so we could find best solution for that

**Comment by athlonUA** [comment]
@cigolpl  you are right. i want to make additional filtering with these aggregation results like `http://localhost:3050/api/v1/aggregations/collection_name/supplier?search=italy&aggs={"class":["sport_cars"]}`

**Comment by cigolpl** [comment]
@athlonUA cool! it can be useful for many cases. It will be implemented soon

**Comment by athlonUA** [comment]
thanks! :+1:  it will be really cool!

**Comment by cigolpl** [comment]
@athlonUA filtering aggregation is done - #138. You can test it out. Hope works fine ;)

**Comment by athlonUA** [comment]
@cigolpl Good work! :+1:  I will test this feature this night

**Comment by cigolpl** [comment]
@athlonUA great! I am very curious about performance when you are using it with `aggs` or `query`
