### ISSUE TITLE
REST API endpoints

### ISSUE THREAD

**Issue by nengine** [itemsapi/itemsapi#157]
Hi, Elasticsearch already has REST interface and I'm not so sure where this can be useful.  I'm developing express.js to integrate with ES, but not so sure which one to use.  Thanks a lot!

**Comment by cigolpl** [comment]
In many cases it makes totally sense to use native elasticsearch because you have access to more advanced functionality like `fuzzy query`, `nested aggregations` and you are not dependent on 3rd party systems. Integration with Express.js should be also easy to go.

In terms of ItemsAPI:
- ES is great for many things like analytics, logs, search, statistics and because of it, it is easy to be distracted by functionality overhead (at least for me in the beginning)
- In ItemsAPI you have very limited and simplified functionality of ES designed only for web & mobile application (filters, sorting, search, auto-generated backend)
- Once using ItemsAPI you don't need to know Elasticsearch (probably except defining schema).
- Once using ItemsAPI you can also use native elasticsearch search query if you miss some functionality
- There is also a dashboard for ItemsAPI https://github.com/itemsapi/dashboard which allows you to add and explore your data out of the box
- If you use Express.js there is also a client for Node.js https://github.com/itemsapi/itemsapi-node

So ItemsAPI can be good for fast prototyping, building catalogs, SEO optimized websites and web applications in general and Elasticsearch for more advanced and more complex. On the other hand ES is more mature and ItemsAPI still in development mode

**Comment by nengine** [comment]
@cigolpl Thank you for your reply.
