### ISSUE TITLE
Elasticsearch 5.x

### ISSUE THREAD

**Issue by faizalpribadi** [itemsapi/itemsapi#176]
Are the team get prepared `itemsapi` supported to elasticsearch 5 ?

**Comment by cigolpl** [comment]
The main focus in the beginning was creating search engine which is very easy to use and easy to start working with. There was unfortunately no plan for covering all or most elasticsearch versions. I am sorry

**Comment by piotrkochan** [comment]
You should add information about Elasticsearch compatibility to the README

**Comment by cigolpl** [comment]
@piotrkochan you are right! I've updated readme

**Comment by valentinedwv** [comment]
End of life schedule:
https://www.elastic.co/support/eol

**Comment by cigolpl** [comment]
@valentinedwv thanks for link. I am aware ItemsAPI is using old 1.7 ES version... but FYI personally I am not planning to upgrade ItemsAPI to ES 2.x, 5.x or 6.x in the nearest feature because it will not improve performance, security or other things. The API of ItemsAPI with ES 1.x or later versions will be quite the same so as far as it is possible to install ES 1.7 it's fine for me

Anyway if someone is interested in supporting different ES version you can add "patches" to https://github.com/itemsapi/elasticitems. Then if ElasticItems works with different ES versions we could create ItemsAPI 2.0 which works over ElasticItems (API over NPM module)
