### ISSUE TITLE
Ability to import / use mapping from existed elasticsearch index

### ISSUE THREAD

**Issue by pilot** [itemsapi/itemsapi#50]

**Comment by pjedrzejewski** [comment]
That would pretty neat indeed. :+1: 

I can imagine using this as a standalone browser for Sylius' ElasticSearch index - would be awesome use case.

**Comment by cigolpl** [comment]
Yes, that's great idea :+1: 
@pjedrzejewski I am happy about new use case :)

Which importing interface would you suggest ?
Importing from CLI by providing elasticsearch URL `'http://localhost:9200/_all/_mapping/tweet,book'` should be enough (at least in the beginning) ?

**Comment by pilot** [comment]
yes, CLI import is enough

**Comment by pjedrzejewski** [comment]
Yes, let's always start with simple solution, that saves you a lot of headache cause ideas evolve as you work on implementing them. CLI is definitely enough and already awesome!

**Comment by cigolpl** [comment]
@pjedrzejewski yes, sounds good :)

#51 here is a merged solution to this ticket.

From now we can import type to the local collections database:
1. Set your elasticsearch URL in `config/local.json`
// see your elasticsearch statistics (indexes)
2. `node cli.js --elasticsearch --indices`
// see your mappings (type and index is optional)
3. `node cli.js --elasticsearch --mapping --type=city --index=project`
// import specific type to the local collections db (if you don't provide `type` it will take the first mapping)
2. `node cli.js --elasticsearch --import --type=movie`

It should works fine except in some routes we have hardcoded (index) `project="project"` instead of value from configurations.

**Comment by pjedrzejewski** [comment]
Nice! Added to the documentation? :)

**Comment by cigolpl** [comment]
Yes @pjedrzejewski. Thanks, I have already added it. New content is here: https://itemsapi.readme.io/docs/cli
